nodes:
  - name: smartystreets_ruby
    image: smartystreets_ruby
  - name: smartystreets_jruby
    image: smartystreets_jruby
steps:
  - name: build_parallel
    type: parallel
    steps:
    - name: build_smartystreets_ruby
      type: build
      image_name: smartystreets_ruby
      build_file_path: Dockerfile.ruby-2.2.0
    - name: build_smartystreets_jruby
      type: build
      image_name: smartystreets_jruby
      build_file_path: Dockerfile.jruby-1.7.19
  - name: provision_parallel
    type: parallel
    steps:
    - name: provision_ruby
      type: run
      node:
        name: smartystreets_ruby
      commit: smartystreets_ruby:provision
      command: bundle install -j8
    - name: provision_jruby
      type: run
      node:
        name: smartystreets_jruby
      commit: smartystreets_jruby:provision
      command: bundle install -j8
  - name: test_parallel
    type: parallel
    steps:
    - name: test_ruby
      type: run
      node:
        name: smartystreets_ruby:provision
      command: bundle exec rake
    - name: test_jruby
      type: run
      node:
        name: smartystreets_jruby:provision
      command: bundle exec rake
