nodes:
  - name: libsmartystreets
    image: libsmartystreets
  - name: ubuntu:trusty
    image: ubuntu:trusty
    env:
      FOO: bar
steps:
  - name: libsmartystreets
    type: build
    image_name: libsmartystreets
    build_file_path: Dockerfile
    configure:
      node:
        name: ubuntu:trusty
      command: bash .codeship/echo_foo.sh foo_output.txt
  - name: echo_foo
    type: run
    node:
      name: libsmartystreets
    command: cat foo_output.txt
  - name: only_codeship
    tag: codeship
    type: run
    node:
      name: libsmartystreets
    command: echo THIS SHOULD ONLY BE RUN ON THE CODESHIP TAG
  - name: only_master
    tag: master
    type: run
    node:
      name: libsmartystreets
    command: echo THIS SHOULD ONLY BE RUN ON THE MASTER TAG
  - name: parallel_stuff
    type: parallel
    steps:
      - name: pwd
        type: run
        node:
          name: libsmartystreets
        command: pwd
      - name: ls
        type: run
        node:
          name: libsmartystreets
        command: ls
      - name: parallel_recursive
        type: parallel
        steps:
          - name: echo_something
            type: run
            node:
              name: libsmartystreets
            command: echo something
          - name: echo_something_else
            type: run
            node:
              name: libsmartystreets
            command: echo something_else
  - name: provision
    type: run
    node:
      name: libsmartystreets
    commit: libsmartystreets:provision
    command: bundle install -j8
  - name: test
    type: run
    node:
      name: libsmartystreets:provision
    command: bundle exec rake
