nodes:
  smartystreets_ruby:
    build:
      image: smartystreets_ruby
      dockerfile_path: Dockerfile.ruby-2.2.0
  smartystreets_jruby:
    build:
      image: smartystreets_jruby
      dockerfile_path: Dockerfile.jruby-1.7.19
steps:
  - name: test_parallel
    type: parallel
    steps:
    - name: test_ruby
      type: run
      node: smartystreets_ruby
      command: bundle exec rake
    - name: test_jruby
      type: run
      node: smartystreets_jruby
      command: bundle exec rake
